import Providers from '@/providers/Providers';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { APP_INFO } from '@/utils/constants';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: APP_INFO.appName,
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='es'>
			<body className={montserrat.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
